branch: main
check:
  - CKV_GCP_1
  - CKV_GCP_2
  - CKV_GCP_3
  - CKV_GCP_4
  - CKV_GCP_6
  - CKV_GCP_7
  - CKV_GCP_8
  - CKV_GCP_9
  - CKV_GCP_10
  - CKV_GCP_11
  - CKV_GCP_12
  - CKV_GCP_13
  - CKV_GCP_14
  - CKV_GCP_15
  - CKV_GCP_16
  - CKV_GCP_17
  - CKV_GCP_18
  - CKV_GCP_19
  - CKV_GCP_20
  - CKV_GCP_21
  - CKV_GCP_22
  - CKV_GCP_23
  - CKV_GCP_24
  - CKV_GCP_25
  - CKV_GCP_26
  - CKV_GCP_27
  - CKV_GCP_28
  - CKV_GCP_29
  - CKV_GCP_30
  - CKV_GCP_31
  - CKV_GCP_32
  - CKV_GCP_33
  - CKV_GCP_34
  - CKV_GCP_35
  - CKV_GCP_36
  - CKV_GCP_37
  - CKV_GCP_38
  - CKV_GCP_39
  - CKV_GCP_40
  - CKV_GCP_41
  - CKV_GCP_42
  - CKV_GCP_44
  - CKV_GCP_45
  - CKV_GCP_46
  - CKV_GCP_47
  - CKV_GCP_48
  - CKV_GCP_49
  - CKV_GCP_50
  - CKV_GCP_51
  - CKV_GCP_52
  - CKV_GCP_53
  - CKV_GCP_54
  - CKV_GCP_55
  - CKV_GCP_56
  - CKV_GCP_57
  - CKV_GCP_58
  - CKV_GCP_59
  - CKV_GCP_60
  - CKV_GCP_61
  - CKV_GCP_62
  - CKV_GCP_63
  - CKV_GCP_64
  - CKV_GCP_65
  - CKV_GCP_66
  - CKV_GCP_68
  - CKV_GCP_69
  - CKV_GCP_70
  - CKV_GCP_71
  - CKV_GCP_72
  - CKV_GCP_73
  - CKV_GCP_74
  - CKV_GCP_75
  - CKV_GCP_76
  - CKV_GCP_77
  - CKV_GCP_78
  - CKV_GCP_79
  - CKV_GCP_80
  - CKV_GCP_81
  - CKV_GCP_83
  - CKV_GCP_84
  - CKV_GCP_85
  - CKV_GCP_86
  - CKV_GCP_87
  - CKV_GCP_88
  - CKV_GCP_89
  - CKV_GCP_90
  - CKV_GCP_91
  - CKV_GCP_92
  - CKV_GCP_93
  - CKV_GCP_94
  - CKV_GCP_95
  - CKV_GCP_96
  - CKV_GCP_97
  - CKV_GCP_98
  - CKV_GCP_99
  - CKV_GCP_100
  - CKV_GCP_101
  - CKV_GCP_102
  - CKV_GCP_103
  - CKV_GCP_104
  - CKV_GCP_105
  - CKV_GCP_106
  - CKV_GCP_107
  - CKV_GCP_108
  - CKV_GCP_109
  - CKV_GCP_110
  - CKV_GCP_111
  - CKV_GCP_112
  - CKV_GCP_113
  - CKV_GCP_114
  - CKV_GCP_115
  - CKV_GCP_116
  - CKV_GCP_117
  - CKV2_GCP_1
  - CKV2_GCP_2
  - CKV2_GCP_3
  - CKV2_GCP_4
  - CKV2_GCP_6
  - CKV2_GCP_7
  - CKV2_GCP_8
  - CKV2_GCP_9
  - CKV2_GCP_11
  - CKV2_GCP_12
  - CKV2_GCP_13
  - CKV2_GCP_14
  - CKV2_GCP_15
  - CKV2_GCP_16
  - CKV2_GCP_17
  - CKV2_GCP_18
  - CKV2_GCP_19
  - CKV2_GCP_20
download-external-modules: true
framework: terraform
output: sarif
skip-check:
  - CKV_TF_1
  - CKV_GCP_118
  - CKV2_GCP_5
  - CKV_GCP_82
  - CKV2_GCP_10
  - CKV_GCP_43
