name: Admin Manual trigger Do not touch!!
on: 
  workflow_dispatch:

jobs:
  management:
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/management_pipeline.yaml