name : pipeline template
on:
  workflow_call:
  push:
    branches:
      - main
jobs:
  terraform-plan:
    name: terraform iac - plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: fmt
        run: terraform init
        working-directory: ./

      - name: Terraform fmt
        id: init
        run: terraform fmt -check
        working-directory: ./

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./

      - id: infracost
        continue-on-error: true
        name: Terraform infracost
        working-directory: ./
        run: |
          echo "## Running infracost" >> $GITHUB_STEP_SUMMARY
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost configure set api_key ${{ secrets.INFRACOST_API_KEY_FREE }}
          infracost configure set currency GBP
          infracost breakdown --path ./terraform.tfplan.json --format=json --out-file=/tmp/infracost.json >> $GITHUB_STEP_SUMMARY
          infracost diff --path ./terraform.tfplan.json --format=json --out-file=/tmp/infracost.json
          infracost comment github --path=/tmp/infracost.json --repo="${{ github.repository }}" --github-token="${{ github.token }}" --pull-request="${{github.event.pull_request.number}}" --behavior=new --show-all-projects

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./

  terraform-apply:
    name: terraform iac - apply
    needs: [terraform-plan]
    runs-on: ubuntu-latest
    environment: terraform-environment
    steps:
      - uses: actions/checkout@v3
    
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: fmt
        run: terraform init
        working-directory: ./

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./
