name : pipeline template
on:
  workflow_call:
  push:
    branches:
      - main
jobs:
  terraform-plan:
    name: terraform iac - plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: fmt
        run: terraform init
        working-directory: ./

      - name: Terraform fmt
        id: init
        run: terraform fmt -check
        working-directory: ./

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=${{ github.workspace }}/tfplan.out
        working-directory: ./

  terraform-apply:
    name: terraform iac - apply
    needs: [terraform-plan]
    runs-on: ubuntu-latest
    environment: terraform-environment
    steps:
      - uses: actions/checkout@v3
    
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: fmt
        run: terraform init
        working-directory: ./

      - name: Terraform Apply
        id: apply
        if: contains(github.event.head_commit.message, 'terraform apply')
        run: terraform apply -auto-approve
        working-directory: ./

      - name: Terraform Destroy
        id: destroy
        if: contains(github.event.head_commit.message, 'terraform destroy')
        run: terraform destroy -auto-approve
        working-directory: ./
