name: 04-platformtools
on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - '04-platformtools/**'
jobs:
  management:
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'
    uses: ./.github/templates/pipeline_template.yaml
    secrets: inherit
    with:
      working-directory: 04-platformtools
      workload-identity-provider: projects/271270271496/locations/global/workloadIdentityPools/github-b-control-pool/providers/github-b-control-provider
      workload-identity-serviceaccount:  sa-control@prj-b-lz-seed-er1w.iam.gserviceaccount.com
