name: Terratest
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  management:
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'
    uses: ./.github/templates/test_execution_pipeline.yaml
    secrets: inherit
    with:
      working-directory: terratest/test
      workload-identity-provider: projects/271270271496/locations/global/workloadIdentityPools/github-b-control-pool/providers/github-b-control-provider
      workload-identity-serviceaccount: sa-control@prj-b-lz-seed-er1w.iam.gserviceaccount.com
